# Generated by Django 5.1.3 on 2024-11-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionData',
            fields=[
                ('key', models.IntegerField(unique=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('lore', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SkinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='champions.championdata')),
            ],
        ),
        migrations.CreateModel(
            name='SpellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tooltip', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=200)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='champions.championdata')),
            ],
        ),
    ]
